# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI and SonarQube Analysis

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - name: Create config.py file
      shell: bash
      run: |
        cat << EOF > config.py
        PATH="not_used_in_pytest"
        GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}"
        TMDB_API_KEY="${{ secrets.TMDB_API_KEY }}"
        MAIL="${{ secrets.MAIL }}"
        MAIL_PSWD="${{ secrets.MAIL_PSWD }}"
        EOF

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests and Generate Coverage
      run: |
        pytest --cov=src --cov-report=xml

    # upload coverage file when os is ubuntu
    - name: Upload coverage artifact
      if: matrix.os == 'ubuntu-latest' 
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
        include-hidden-files: true
        retention-days: 1

  sonarqube:
    name: SonarQube Scan
    needs: test 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download coverage artifact
      uses: actions/download-artifact@v4
      with:
        name: coverage-report

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}